#!/bin/bash

## argument 1 is the image / movie name
## argument 2 is the first cell (default 0)
first_cell=${2:-0}

~/ffmpeg -start_number ${first_cell} -i ${1}.%4d.png -vf fps=60 -pix_fmt yuv420p ${1}.mp4
