#!/bin/bash

## 1 is the image / movie name

~/ffmpeg -i ${1}.%4d.png -vf fps=60 -pix_fmt yuv420p ${1}.mp4
#~/ffmpeg -i ${1}.%4d.png -c:v libx264 -vf fps=10 -pix_fmt yuv420p ${1}.mp4
#~/ffmpeg -i ${1}.%04d.png -c:v libx264  -pix_fmt yuv420p ${1}.mp4
