#!/bin/bash -e

DATA_HOME=/mnt/ceph/users/mokounkova/Kerrness_0p0_0p0_q1
Lev=2
OBS_DIR="Observation_$(basename $DATA_HOME)_Lev${Lev}"
echo $OBS_DIR
mkdir $OBS_DIR
MPIRUN=$(GetMpiCmd -p 48)
keep=$(pwd)

## Run apply observers on the dirs
cd ${DATA_HOME}/Ev
for dir in Lev${Lev}_[A-Z][A-Z] #Lev${Lev}_Ringdown/Lev${Lev}_[A-Z][A-Z]
do
  echo ${dir}
  if [ ! -f ${dir}/Run/Vars* ]; then
    echo "No volume data for ${dir}"
    continue
  fi
  echo "Processing volume data for ${dir}"
  cd ${keep}
  mkdir -p ${dir}
  cd ${dir}
  cp ${keep}/ApplyObservers.input .
  cp $DATA_HOME/Ev/${dir}/Run/Hist-Func* .
  cp $DATA_HOME/Ev/${dir}/Run/SpatialCoordMap.input .
  $MPIRUN ApplyObservers -t psi,kappa -r 11,122 -d 4,4 -dir "${DATA_HOME}/Ev/${dir}/Run" -domaininput "GrDomain.input" -v ApplyObservers.input
  cd ${keep}
done

## Combine the directories
cat Lev${Lev}_[A-Z][A-Z]/DataVtk.pvd >> ${OBS_DIR}/DataVtk.pvd
cat Lev${Lev}_Ringdown/Lev${Lev}_[A-Z][A-Z]/DataVtk.pvd >> ${OBS_DIR}/DataVtk.pvd
~/KerrnessBinaries/CleanVtk ${OBS_DIR}/DataVtk.pvd
mkdir ${OBS_DIR}/DataVtk
mv Lev${Lev}_[A-Z][A-Z]/DataVtk/* ${OBS_DIR}/DataVtk
mv Lev${Lev}_Ringdown/Lev${Lev}_[A-Z][A-Z]/DataVtk/* ${OBS_DIR}/DataVtk

